@DoAnTotNghiep.Web_HostAddress = https://localhost:5017
### Create User
POST http://localhost:5017/api/auth/register
Content-Type: application/json

{
  "username": "huytran",
  "email": "huytran11@example.com",
  "password": "123456"
}

### Forgot password
POST http://localhost:5017/api/auth/forgot-password
Content-Type: application/json

{
  "email": "huytran11@example.com"
}
