### Create User

POST http://localhost:5017/api/users
Content-Type: application/json

{
  "username": "huytran",
  "age": 22,
  "gender": 0,
  "email": "[huytran@example.com](mailto:huytran@example.com)",
  "phone": "0912345678",
  "password": "123456"
}
