apiVersion: apps/v1
kind: Deployment
metadata:
  name: datn2026-stt43-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: ghcr.io/hiamchubbybear/datn2026-stt43-backend:latest
          ports:
            - containerPort: 5050
          envFrom:
            - configMapRef:
                name: backend-config
            - secretRef:
                name: backend-secret
