apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: datn2026-stt43
type: Opaque
stringData:
  MongoDb__ConnectionString: mongodb+srv://chessy:d2YEPi7Y1MkXMcG0@tinder-clone.manxzke.mongodb.net/?appName=Tinder-Clone
  Redis__ConnectionString: datn-redis-service:6379
  RabbitMQ__HostName: rabbitmq
  RabbitMQ__UserName: admin
  RabbitMQ__Password: admin123
  Secret__GmailNotification: pmdk wiux aqws uoxq
  Oauth2__Google__ClientId: 96114439282-miec2ccuboqf5naulqek4lf4l2ug9amh.apps.googleusercontent.com
  Oauth2__Google__ClientSecret: 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
