
FROM reactnativecommunity/react-native-android:latest

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm ci

COPY . .

RUN npx expo prebuild --platform android --clean

WORKDIR /app/android
RUN chmod +x gradlew

RUN ./gradlew assembleRelease
